// Generated by ts2civet: Tue Jul 04 2023 15:56:04 GMT+0200 (Central European Summer Time)

import { hello } from "./hello.js"


tag: console.log('tagged!')
$: 
	console.log('svelty!')



console.log(hi, hey, hello)
@Object.seal
class Civet {
	static name = 'Civet'
	@description(translate('Caffeine time!'))
	drink() {
		return this.fetch(this.coffeeCup)
	}
}




implicit(call(1), call(2, 3))
implicit(call(3))
keepExplicit()
keepExplicit(call(4)).thingy
